### ISSUE TITLE
Repeater will not Wake up

### ISSUE THREAD

**Issue by do1kbl** [OK-DMR/Hytera_Homebrew_Bridge#10]
2020.4 --> Hytera Repeater will not Wake Up from incomming Traffic from the HBlink3 Server.
But Ethernet lights will Flashing fast

Test on RD625 with FW: 8.5

**Comment by smarek** [comment]
This should be fixed now, because packets were malformed and repeater throws them away instead of waking up.
Please check again with 2021.1 i've just released

**Comment by smarek** [comment]
Closed per email confirmation it works with 2021.1
