### ISSUE TITLE
Hytera RD625 Firmware 9.02 does not connect master BM.

### ISSUE THREAD

**Issue by Dmedia3412** [OK-DMR/Hytera_Homebrew_Bridge#11]
Hytera RD625 Firmware 9.02
DMRGateway-20200421

does not connect master BM.

NFO - 2021-11-09 00:55:06,915 - MMDVMProtocol - -------- MMDVM CONFIGURATION PACKET --------
DEBUG - 2021-11-09 00:55:06,915 - MMDVMProtocol - MFQ  Unsupported common_log_format for data TypeRepeaterConfigurationOrClosing
INFO - 2021-11-09 00:55:06,922 - MMDVMProtocol - Master accepted our configuration
DEBUG - 2021-11-09 00:55:08,801 - MMDVMProtocol - Sending PING
DEBUG - 2021-11-09 00:55:08,803 - MMDVMProtocol - MFQ  Unsupported common_log_format for data TypeRepeaterPing
DEBUG - 2021-11-09 00:55:08,813 - MMDVMProtocol - Master PONG received
DEBUG - 2021-11-09 00:55:12,187 - HyteraMmdvmTranslator - HYTERA->MMDVM Received IPSC Heartbeat, not translating
DEBUG - 2021-11-09 00:55:13,804 - MMDVMProtocol - Sending PING
DEBUG - 2021-11-09 00:55:13,805 - MMDVMProtocol - MFQ  Unsupported common_log_format for data TypeRepeaterPing
DEBUG - 2021-11-09 00:55:13,815 - MMDVMProtocol - Master PONG received
DEBUG - 2021-11-09 00:55:18,810 - MMDVMProtocol - Sending PING
DEBUG - 2021-11-09 00:55:18,811 - MMDVMProtocol - MFQ  Unsupported common_log_format for data TypeRepeaterPing
DEBUG - 2021-11-09 00:55:18,812 - MMDVMProtocol - Master PONG received
DEBUG - 2021-11-09 00:55:19,150 - HyteraMmdvmTranslator - HYTERA->MMDVM Received IPSC Heartbeat, not translating

DMRGateway log

M: 2021-11-08 19:46:30.883 DMRGateway-20200421 is running
D: 2021-11-08 19:46:40.926 BM, Sending authorisation
D: 2021-11-08 19:46:40.968 BM, Sending configuration
E: 2021-11-08 19:46:41.011 BM, Login to the master has failed, retrying network ...
M: 2021-11-08 19:46:41.011 BM, Closing DMR Network
M: 2021-11-08 19:46:41.011 BM, Opening DMR Network
D: 2021-11-08 19:46:51.062 BM, Sending authorisation
D: 2021-11-08 19:46:51.104 BM, Sending configuration
E: 2021-11-08 19:46:51.147 BM, Login to the master has failed, retrying network ...
M: 2021-11-08 19:46:51.147 BM, Closing DMR Network
M: 2021-11-08 19:46:51.147 BM, Opening DMR Network
D: 2021-11-08 19:47:01.183 BM, Sending authorisation
D: 2021-11-08 19:47:01.216 BM, Sending configuration
E: 2021-11-08 19:47:01.258 BM, Login to the master has failed, retrying network ...
M: 2021-11-08 19:47:01.258 BM, Closing DMR Network
M: 2021-11-08 19:47:01.259 BM, Opening DMR Network
D: 2021-11-08 19:47:11.301 BM, Sending authorisation
D: 2021-11-08 19:47:11.334 BM, Sending configuration
E: 2021-11-08 19:47:11.366 BM, Login to the master has failed, retrying network ...
M: 2021-11-08 19:47:11.366 BM, Closing DMR Network

Please tell me if you tested on firmware 9.02 ?

**Comment by smarek** [comment]
Short answer: No, this is not tested with firmware 9.x, but it should work, if you replace RDAC with SNMP and static configuration (RDAC is used only for getting name, frequency, radio mode, etc...)

Long answer: 
  1. I don't see any logs, that say HHB is the faulting component here
  2. Logs are truncated I need complete logs from HHBridge and DMRGateway to be able to tell you more, and if you don't want to put the public, you can send them to me by email
  3. DMRGateway says "Try to login ; Login failed ; Try to login ; Login failed ; ..." which looks more like BM/SelfCare account issue, why do you think it's HHB issue?

**Comment by Dmedia3412** [comment]
package_id = MMDVM_Hytera_Homebrew_Bridge

this solved my connection problem

**Comment by smarek** [comment]
What? What do you mean by "hardware line" ? Is this solution something required by BM?

**Comment by Dmedia3412** [comment]
This corrected line "package_id = MMDVM_Hytera_Homebrew_Bridge" in settings.ini file let me successfully connect to BM master.

`Hytera_Homebrew_Bridge (MMDVM)`

 this is displayed on the repeater information page in BM

**Comment by smarek** [comment]
I understand the solution, but not the reason why it fixes anything. Does BM require you to use specific software identifier for it to let you connect?

**Comment by Dmedia3412** [comment]
I don't know what BM requires. As it seems to me, this MMDVM_ entry allows you to go through the whitelist of applications that are allowed by the BM. This is what helped me connect successfully.

**Comment by smarek** [comment]
Thanks for clarification

**Comment by smarek** [comment]
So I've just tested with R9.0 and R9.2 firmwares, both successfull

For other visitors of this issue, your issue might be solved by using `package_id = MMDVM_Hytera_Homebrew_Bridge` in `settings.ini` file
