### ISSUE TITLE
Always BER 36%

### ISSUE THREAD

**Issue by Dmedia3412** [OK-DMR/Hytera_Homebrew_Bridge#13]
Any transmission sends to BM, BER 36% in signal strength line. The sound has artifacts.

**Comment by smarek** [comment]
Voice quality is not good currently, should get better with next release. How do you measure BER ? Is it shown by BM or DMRGateway ?

**Comment by Dmedia3412** [comment]
Yes, this is statistics from the BM site.

**Comment by smarek** [comment]
Could you test with latest version from **develop** branch? I think I've fixed the issue that causes this

**Comment by smarek** [comment]
This should be solved, reopen if you still experience difficulties, please
