### ISSUE TITLE
Repeater activation

### ISSUE THREAD

**Issue by do1kbl** [OK-DMR/Hytera_Homebrew_Bridge#6]
When a new run starts and the repeater is in idle mode, there will be 1-2 seconds of audio missing

**Comment by smarek** [comment]
With each call, or just the first one?

**Comment by do1kbl** [comment]
I think its the first call. When the Repeater need to wake up.
If the Repeater activ on TX I head not the Problem.

I write a small Programm to sent the time every full Hour like "Its 11 o´clock"  When this programm start with Kurts GW its OK
With your gateway you hear only "11O´clock" the "its" is missing.

**Comment by smarek** [comment]
I'll see about the timing of VOICE_LC_HEADER, maybe wait a bit between VOICE_LC_HEADER and first VOICE frame? 
Thank you for testing, this will get fixed as well

**Comment by smarek** [comment]
I've added WAKEUP packets (SlotType 0xDDDD) and if it's first call or first call after long time (60sec timeout) it will get sent first, to wakeup the repeater
