### ISSUE TITLE
Ping Pong with Repeater and Update the QRG and RadioID 

### ISSUE THREAD

**Issue by do1kbl** [OK-DMR/Hytera_Homebrew_Bridge#7]
If the Repeater lost the network connection, it looks like the software will not detect it and is not logoff from mmdvm_Server

**Comment by do1kbl** [comment]
The Radio ID anf Frequency will not overwrite the data from .ini file

This is WORKING, it was my Fault!

**Comment by smarek** [comment]
> If the Repeater lost the network connection, it looks like the software will not detect it and is not logoff from mmdvm_Server

You mean, when MMDVM/HBlink disconnects, HHBridge does not reconnect, or when repeater disconnects it should disconnect from MMDVM/HBlink server?
Former should not happen, there is maintenance routine
Latter is not meant to happen, as losing repeater connection does not mean it should disconnect from mmdvm/hblink master

**Comment by smarek** [comment]
> The Radio ID and Frequency will not overwrite the data from .ini file
> 
> This is WORKING, it was my Fault!

Different issue probably? Please keep one ticket for one issue/topic. Glad this is not a problem, again, if it was your fault, how did you fix it? I'd like to add that to FAQ

**Comment by do1kbl** [comment]
> 
> 
> > If the Repeater lost the network connection, it looks like the software will not detect it and is not logoff from mmdvm_Server
> 
> You mean, when MMDVM/HBlink disconnects, HHBridge does not reconnect, or when repeater disconnects it should disconnect from MMDVM/HBlink server?
> Former should not happen, there is maintenance routine
> Latter is not meant to happen, as losing repeater connection does not mean it should disconnect from mmdvm/hblink master

Yes HBLink its not the Problem.
I mean if the Hytera Repeater lost the connection, we have no information about it in the logging. Maybe Its a solution if the Hytera disconnected or lost connection we have a information into the logging or the HBlink will also disconnect that we can see something with the Repeater its not OK.

**Comment by smarek** [comment]
Well, it does not exactly disconnect. It's UDP transport not TCP server.
I can log if there was no packet (keepalive/IPSC heartbeat) received for a long time (that would mean the repeater lost connectivity / was turned off / ...)
I can send REPEATER_CLOSING message to HBLINK/MMDVM and wait for repeater to connect again under such conditions. Would that be helpful?

**Comment by do1kbl** [comment]
maybe with a config bit? ClosedHBIfRepeaterlost ? yes/no
I think the logging its very Helpfull.
Closed the hb connection its an option maybe with confing? What you think?

if the repeater is somewhere, you cannot check whether it is working, you can only see that HB_Client is connected to the server but the repeater no longer sends.

**Comment by smarek** [comment]
I think I can close the MMDVM if no Hytera repeater is connected, not on disconnect of single one, because i'm planning on adding support for bridging multiple repeaters, see #5 
Yes, the config will be necessary, thank you

**Comment by smarek** [comment]
I've added logging the SNMP obtained configuration and breakdown of MMDVM sent configuration, so you can check if the data merges correctly within HHB settings

**Comment by smarek** [comment]
I've added the request to #5 on todo-list, so this can be closed now
